---
- name: install applications
  hosts: localhost
  environment:
        GOPATH: "{{ lookup('env','HOME') }}/.go"
  tasks:
    # - name: add apt source for "cassandra"
    #   shell: echo "deb http://www.apache.org/dist/cassandra/debian 36x main" |  tee -a /etc/apt/sources.list.d/cassandra.list
    # - name: add pgp keys for "cassandra"
    #   shell: "gpg --keyserver pgp.mit.edu --recv-keys 749D6EEC0353B12C && gpg --export --armor 749D6EEC0353B12C | apt-key add -"
    # - name: Update repositories cache and install "cassandra" package
    #   apt:
    #     name: cassandra
    #     update_cache: yes


    # file structure      
    ## var
    - name: "var base directory"
      file: path="/root/var" owner="root" group="staff" state="directory"
    - name: "var base directory"
      file: path="/root/var" owner="root" group="staff" state="directory"
    - name: "var cache"
      file: path="/root/var/cache" owner="root" group="staff" state="directory"
    - name: "var state information"
      file: path="/root/var/lib" owner="root" group="staff" state="directory"
    - name: "var lock files"
      file: path="/root/var/lock" owner="root" group="staff" state="directory"
    - name: "var logs"
      file: path="/root/var/log" owner="root" group="staff" state="directory"
    - name: "var opt application files"
      file: path="/root/var/opt" owner="root" group="staff" state="directory"
    - name: "var boot information"
      file: path="/root/var/run" owner="root" group="staff" state="directory"
    - name: "var tmp files"
      file: path="/root/var/tmp" owner="root" group="staff" state="directory"
    ## srv
    - name: "src, git/http/application servers"
      file: path="/root/srv" owner="root" group="staff" state="directory"
    ## etc
    - name: "configuration for locally built applications"
      file: path="/root/etc" owner="root" group="staff" state="directory"
    ## opt
    - name: "dev versions of software, continuously rebuilt for resting"
      file: path="/root/opt" owner="root" group="staff" state="directory"
    ## pull-requests
    - name: "dev versions of software, manual VC pull"
      file: path="/root/pull-requests" owner="root" group="staff" state="directory"
    ## zsh
    - name: "dev versions of software, manual VC pull"
      file: path="/root/.zsh.d" owner="root" group="staff" state="directory"
    # setup crontabs
    - name: "run ansible playbooks"
      cron: name="crontab generate crontabs" minute="20" user="root" job="/root/etc/ansible/bin/run-playbook"
    # emacs
    - name: add modern "emacs" ppa
      apt_repository:
        repo: ppa:kelleyk/emacs
    - name: Update repositories cache and install "emacs26-nox" package
      apt:
        name: emacs26
        update_cache: yes
    # python
    - name: install "python-setuptools" 
      apt:
        name: python-setuptools
    - name: install "python-dev" 
      apt:
        name: python-dev
    - name: install "pip"
      shell: easy_install pip
      
    # prometheus
    - name: Update repositories cache and add "golang-1.10" ppa
      apt_repository:
        repo: ppa:longsleep/golang-backports
    - name: Update repositories cache and install "golang-1.10" package
      apt:
        name: golang-go
        update_cache: yes
    - name: go get "prometheus"
      shell: go get github.com/prometheus/prometheus/cmd/...

    # postgresql
    - name: Update repositories cache and install "postgresql" package
      apt:
        name: postgresql

    - name: Update repositories cache and install "postgresql-contrib" package
      apt:
        name: postgresql-contrib
    # couchbase
    # - name: download "couchbase"
    #   shell: wget https://packages.couchbase.com/releases/5.0.1/couchbase-server-community_5.0.1-ubuntu16.04_amd64.deb
    # - name: install "couchbase"
    #   shell: dpkg -i couchbase-server-community_5.0.1-ubuntu16.04_amd64.deb

    # orientdb
    # - name: download "orientdb"
    #   shell: wget -O orientdb-community-2.2.20.tar.gz "http://orientdb.com/download.php?file=orientdb-community-2.2.20.tar.gz&os=linux" && tar xvf orientdb-community-2.2.20.tar.gz
    # - name: install "orientdb"
    #   shell: mv ~/orientdb-community-2.2.20 /opt/orientdb

    # cassandra
    # - name: add apt source for "cassandra"
    #   shell: echo "deb http://www.apache.org/dist/cassandra/debian 36x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.list
    # - name: add pgp keys for "cassandra"
    #   shell: "gpg --keyserver pgp.mit.edu --recv-keys 749D6EEC0353B12C && gpg --export --armor 749D6EEC0353B12C | sudo apt-key add -"

      # https://packages.couchbase.com/releases/5.1.1/couchbase-server-community_5.1.1-ubuntu16.04_amd64.deb

    # cassandra

