 - name: lua
   hosts: localhost
   tasks:
     - name: download "install fennel"
       shell: luarocks install --server=http://luarocks.org/dev fennel
#     - name: installing perl module "local::lib"
#       cpanm:
#         name: local::lib
#         locallib: ~/perl5

#     - name: install perl module "IO::All"
#       cpanm:
#         name: IO::All
#         locallib: ~/perl5

#     - name: install perl module "Net::MAC"
#       cpanm:
#         name: Net::MAC
#         locallib: ~/perl5

#     - name: install perl module "HTTP::Status"
#       cpanm:
#         name: HTTP::Status
#         locallib: ~/perl5

      
